project:
  type: website

website:
  title: "Adrien Bouissou"
  navbar:
    left:
      - about.qmd
    tools:
      - icon: linkedin
        href: https://linkedin.com/in/abouissou
      - icon: github
        href: https://github.com/abouissou
  search: false

format:
  html:
    theme: default
    css: styles.css
    toc: true
